annotation(b-location,[ad�]).
annotation(b-location,[ad�ye]).
annotation(b-location,[ayd�n]).
annotation(b-location,[ayd�na]).
annotation(b-location,[ayd�ndan]).
annotation(b-location,[bozdo�an]).
annotation(b-location,[bozdo�ana]).
annotation(b-location,[bozdo�andan]).
annotation(b-location,[derea�z�]).
annotation(b-location,[efeler]).
annotation(b-location,[efelerden]).
annotation(b-location,[efelere]).
annotation(b-location,[germencik]).
annotation(b-location,[germencike]).
annotation(b-location,[germencikten]).
annotation(b-location,[hisar]).
annotation(b-location,[imamk�y]).
annotation(b-location,[incirliova]).
annotation(b-location,[incirliovadan]).
annotation(b-location,[incirliovaya]).
annotation(b-location,[karacasu]).
annotation(b-location,[karacasudan]).
annotation(b-location,[karacasudur]).
annotation(b-location,[karacasuya]).
annotation(b-location,[karasudur]).
annotation(b-location,[karde�k�y]).
annotation(b-location,[karpuzludan]).
annotation(b-location,[karpuzluya]).
annotation(b-location,[ko�arl�]).
annotation(b-location,[ko�arl�dan]).
annotation(b-location,[ko�arl�ya]).
annotation(b-location,[kuyucak]).
annotation(b-location,[kuyucaka]).
annotation(b-location,[kuyucaktan]).
annotation(b-location,[ku�adas�]).
annotation(b-location,[ku�adas�d�r]).
annotation(b-location,[ku�adas�na]).
annotation(b-location,[k�z�lcak�y]).
annotation(b-location,[meydan�]).
annotation(b-location,[nazilli]).
annotation(b-location,[nazilliden]).
annotation(b-location,[nazilliye]).
annotation(b-location,[ser�ek�y]).
annotation(b-location,[s�keden]).
annotation(b-location,[s�keye]).
annotation(b-location,[yeni]).
annotation(b-location,[�ine]).
annotation(b-location,[�ineden]).
annotation(b-location,[�inedir]).
annotation(b-location,[�ineye]).
annotation(b-misc,[astim]).
annotation(b-misc,[yolculuk]).
annotation(b-num,[1]).
annotation(b-num,[10.15]).
annotation(b-num,[10]).
annotation(b-num,[11.00]).
annotation(b-num,[11.50]).
annotation(b-num,[11]).
annotation(b-num,[12.05]).
annotation(b-num,[12.20]).
annotation(b-num,[13.20]).
annotation(b-num,[14.05]).
annotation(b-num,[14.20]).
annotation(b-num,[15.35]).
annotation(b-num,[15]).
annotation(b-num,[16.20]).
annotation(b-num,[16.35]).
annotation(b-num,[16.50]).
annotation(b-num,[18.05]).
annotation(b-num,[18.15]).
annotation(b-num,[18.15]).
annotation(b-num,[18.20]).
annotation(b-num,[18.40]).
annotation(b-num,[19.15]).
annotation(b-num,[19.40]).
annotation(b-num,[2.50]).
annotation(b-num,[2.60]).
annotation(b-num,[2.65]).
annotation(b-num,[2.70]).
annotation(b-num,[2.75]).
annotation(b-num,[2.80]).
annotation(b-num,[2.90]).
annotation(b-num,[2]).
annotation(b-num,[20]).
annotation(b-num,[25]).
annotation(b-num,[3.00]).
annotation(b-num,[3.10]).
annotation(b-num,[3.20]).
annotation(b-num,[3.30]).
annotation(b-num,[3.40]).
annotation(b-num,[3.50]).
annotation(b-num,[3.60]).
annotation(b-num,[3.70]).
annotation(b-num,[3.80]).
annotation(b-num,[3.90]).
annotation(b-num,[3]).
annotation(b-num,[30]).
annotation(b-num,[35]).
annotation(b-num,[4.00]).
annotation(b-num,[4.40]).
annotation(b-num,[4.80]).
annotation(b-num,[4]).
annotation(b-num,[40]).
annotation(b-num,[4]).
annotation(b-num,[5.5]).
annotation(b-num,[5]).
annotation(b-num,[50]).
annotation(b-num,[55]).
annotation(b-num,[6.00]).
annotation(b-num,[6.15]).
annotation(b-num,[6]).
annotation(b-num,[605]).
annotation(b-num,[606]).
annotation(b-num,[607]).
annotation(b-num,[608]).
annotation(b-num,[65]).
annotation(b-num,[7.20]).
annotation(b-num,[7.30]).
annotation(b-num,[7]).
annotation(b-num,[8.20]).
annotation(b-num,[8.45]).
annotation(b-num,[9.00]).
annotation(b-num,[9.20]).
annotation(b-num,[9.30]).
annotation(b-num,[9.45]).
annotation(b-person,[h�d�rbeyli]).
annotation(i-location,[hisar]).
annotation(i-location,[hisardan]).
annotation(i-location,[k��k]).
annotation(b-person,[general]).
annotation(i-person,[kenobi]).
